version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./poc.nginx:/etc/nginx/conf.d/poc.conf
    depends_on:
      - test_service
    ports:
      - "8080:8080"
    expose:
      - 8080
  test_service:
    build: ./
    volumes:
      - ./:/opt/test
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      port: "3001"

